# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
# Based template
# https://livedemo00.template-help.com/wt_62272/index.html
title: Ekipa Interiores
email: ekipainteriores@gmail.com
phones: +(505) 2227 0880
address: Camino de Oriente B2-3, N/A, Managua
attention_schedule: "Lunes a Viernes: 9:00 a.m. a 6:00 p.m. - Sábado: 10:00 a.m. a 4:00 p.m."
description: "Muebles de sala, Terraza, Dormitorios, Comedores, Lámparas, Alfombras y demás Accesorios de Decoración que harán de tu casa un lugar bello y cómodo."
baseurl: pymes.ekipainteriores.com # the subpath of your site, e.g. /blog
url: "http://ekipainteriores.com" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username:  ekipainteriores
facebook_username: ekipainteriores
google_analytics: 'UA-101663213-1'

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
